- name: My Super Playbook
  hosts: all
  become: yes

  vars:
    mytext: "Privet ot ADV-IT"

  tasks:
    - name: Ping test
      ping:

    - name: Unregitster Server from Load Balancer
      shell: echo This server {{ inventory_hostname }} was derigestered from our Load Balancer, node name is {{ ansible_nodename }} >> /home/log.txt
      delegate_to: 127.0.0.1

    - name: Update my Databasedd
      shell: echo UPDATE DATABASE
      run_once: true

    - name: Create file1
      copy:
        dest: /home/file1.txt
        content: |
          This is File1
          On ENGLISH Hello World
          On RUSSIAN {{ mytext }}
      delegate_to: linux2

    - name: Create file2
      copy:
        dest: /home/file2.txt
        content: |
          This is File2
          On ENGLISH Hello World
          On RUSSIAN {{ mytext }}

    - name: Reboot my servers
      shell: sleep 3 && reboot now 
      async: 1
      poll: 0

    - name: Wait till my servers will come up online
      wait_for:
          host: "{{ inventory_hostname }}"
          state: started
          delay: 5
          timeout: 69
      delegate_to: 127.0.0.1
