- name: Install default Apache Web Server
  hosts: all
  become: yes

  tasks:
  - name: Install Apache webserver
    apt: name=apache2 state=latest

  - name: Start Apache and Enable it on every boot
    service: name=apache2 state=started enabled=yes

  - name: Check if Apache runs
    ansible.builtin.shell: systemctl is-active apache2
    register: apache_status
    ignore_errors: true

  - name: Output apache status
    ansible.builtin.debug:
      msg: "Apache status: {{ apache_status.stdout }}"
