- name: Install Apache and Upload Web Page
  hosts: STAGING_SERVERS
  become: yes

  vars:
    source_file: ./MyWebSite/test.html
    destin_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Copy HTML page to Servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start WebServer and make it enable
    service: name=apache2 state=started enabled=yes


  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
